const funnyCommits=[
  "Fixed bug that only existed in my mind",
  "Added semicolon because life needs balance",
  "Refactored code to look busy",
  "Deleted 200 lines of useless comments",
  "Oops, forgot to save before commit",
  "Made the code compile, not sure if it works",
  "Optimized something nobody asked for",
  "Added TODOs for my future self",
  "Fixed bug... introduced two more",
  "Because YOLO",
  "Fixed a bug. No idea how, but it works now 🤷",
  "Made the code compile. Functionality is optional.",
  "Deleted half the code… performance improved 🚀",
  "Added a feature nobody asked for 😎",
  "Fixed the fix that fixed the fix 🌀",
  "Debugged in production, like a pro 👨‍💻🔥",
  "99 little bugs in the code, 99 bugs to fix… 🎵",
  "Ship it! We'll fix it later ⛵",
  "Commit first, think later 😬",
  "Refactored code to impress my rubber duck 🦆",
  "Works on my machine 💻✔️",
  "Wrote TODOs I’ll never do 📝",
  "Added comments so future me can suffer less 😅",
  "Renamed variables to confuse my teammates 🤡",
  "Finally removed console.log (probably not)",
];
export default funnyCommits;