const funnyCommits=[
  "Fixed bug that only existed in my mind",
  "Added semicolon because life needs balance",
  "Refactored code to look busy",
  "Deleted 200 lines of useless comments",
  "Oops, forgot to save before commit",
  "Made the code compile, not sure if it works",
  "Optimized something nobody asked for",
  "Added TODOs for my future self",
  "Fixed bug... introduced two more",
  "Because YOLO",
  "Fixed a bug. No idea how, but it works now 🤷",
  "Made the code compile. Functionality is optional.",
  "Deleted half the code… performance improved 🚀",
  "Added a feature nobody asked for 😎",
  "Fixed the fix that fixed the fix 🌀",
  "Debugged in production, like a pro 👨‍💻🔥",
  "99 little bugs in the code, 99 bugs to fix… 🎵",
  "Ship it! We'll fix it later ⛵",
  "Commit first, think later 😬",
  "Refactored code to impress my rubber duck 🦆",
  "Works on my machine 💻",
  "Wrote TODOs I’ll never do 📝",
  "Added comments so future me can suffer less 😅",
  "Renamed variables to confuse my teammates 🤡",
  "Finally removed console.log (probably not)",
  "Works on my machine 💻",
  "Commiting changes I don’t understand",
  "Changed stuff until it broke, then fixed it accidentally",
  "Added console.log for debugging 🔥",
  "Removed console.log for professionalism",
  "Added one line of code, broke everything",
  "Fixed typo in variable name after 2 hours of debugging",
  "Pushed directly to main like a rebel 🤘",
  "Finally fixed the infinite loop... I think",
  "Bug or feature? You decide",
  "The code fairy visited last night ✨",
  "This is fine 🔥🐶",
  "Hotfix for the hotfix",
  "Temporarily fixed it permanently",
  "Moved code around. Now it’s artistic",
  "Added comments that explain nothing",
  "Made naming more confusing",
  "Fixed merge conflict with violence",
  "Here be dragons 🐉",
  "Hacky but it works ¯\\_(ツ)_/¯",
  "Deleted node_modules (again)",
  "Fixed the matrix glitch 🕶️",
  "Updated dependencies. Pray for us 🙏",
  "Wrote code drunk, debugging sober",
  "Magic. Don’t touch ✨",
  "The commit police made me do this 🚨",
  "Turned coffee into code ☕➡️💻",
  "Ship it 🚢",
  "Added Easter egg nobody will find 🥚",
  "Commit message not found 404!",
  "Half-baked feature added 🍞",
  "Accidentally wrote a feature instead of fixing bug",
  "Fixed everything by deleting everything",
  "I have no idea what I'm doing 🐒",
  "Commented out more than I coded",
  "Made Git cry 😢",
  "Cowboy coding 🤠",
  "Fixed one thing, broke ten",
  "Improved performance by making it slower",
  "Linting gods are angry 😡",
  "First try! (not really)",
  "Debugging is just removing 'not' from if statements",
  "Just winging it 🪽",
  "Added memes instead of features",
  "Code written by ChatGPT 🤖",
  "This commit is classified 🕵️",
  "Hired StackOverflow developers 👨‍💻",
  "Fixed bug with duct tape and prayers",
  "CTRL+C CTRL+V driven development",
  "Code quality: questionable 🤔",
  "If it compiles, ship it",
  "Made something that looks like work",
  "The build passed! 🥳",
  "The build failed... but we ignore it 😬",
  "Replaced tabs with spaces (fight me)",
  "Space bar warrior",
  "Tried to center a div, gave up",
  "Improved code readability by deleting it",
  "Reinvented the wheel, square edition ⬛",
  "Everything is temporary, even this commit",
  "Updated README because that’s all I can do",
  "Added feature nobody asked for",
  "Accidental genius or intentional stupidity?",
  "Copy-pasted from StackOverflow",
  "Working prototype (aka total mess)",
  "Fixed bug at 3 AM 🌙",
  "I regret everything about this code",
  "Half commit, half prayer 🙏",
  "Added a feature that breaks another feature",
  "Debugging gods, please help",
  "I’ll fix it tomorrow (never)",
  "Made the code worse but prettier",
  "Added more bugs for job security",
  "Quick fix (aka permanent bug)",
  "Fixed typo in commit message",
  "Accidentally committed my soul to Git",
  "Works on my machine 💻",
  "Fixed bug, created 99 more 🐛",
  "Made the code compile, not sure if it works",
  "Refactored code to look busy",
  "Optimized something nobody asked for",
  "Fixed typo that broke everything",
  "Removed console.log for professionalism",
  "Added console.log for debugging 🔥",
  "Half commit, half prayer 🙏",
  "Copy-pasted from StackOverflow",
  "Added a feature nobody asked for ✨",
  "Bug is now a feature 🐞➡️🚀",
  "Fixed the fix that broke the fix 🔄",
  "Wrote code drunk, debugged sober 🍺",
  "Hotfix for the hotfix 🔥",
  "Renamed variable to something cooler 😎",
  "Temporarily fixed… permanently 🤫",
  "Added console.log because I’m lost 🧭",
  "Deleted half the code, app runs faster ⚡",
  "Hacky but works 🤷‍♂️",
  "Works locally, not in prod 🙃",
  "Commiting like there’s no tomorrow ⏳",
  "Updated README to look busy 📖",
  "Removed code that looked at me funny 👀",
  "Made the linter cry 😢",
  "Refactored until nothing made sense 🔀",
  "Half code, half duct tape 🛠️",
  "Debugging with print statements… again 🖨️",
  "Version bump because why not 🔼",
  "Fixed something… I think 🤔",
  "Accidentally fixed the real bug 😳",
  "99 little bugs in the code 🎶",
  "It’s not a bug, it’s a surprise feature 🎁",
  "Forgot what I was doing, but committed anyway 🤯",
  "Fix works only if you don’t look too closely 👓",
  "Ctrl+C, Ctrl+V driven development ⌨️",
  "This commit is self-aware 🤖",
  "Code so clean it squeaks 🧼",
  "Added unicorns 🦄 to production",
  "Deleted production database, oops 💥",
];

const newfunnyCommits=[...new Set(funnyCommits)];

export default newfunnyCommits;