const funnyCommits = [
  "Fixed bug that only existed in my mind",
  "Added semicolon because life needs balance",
  "Refactored code to look busy",
  "Deleted 200 lines of useless comments",
  "Oops, forgot to save before commit",
  "Made the code compile, not sure if it works",
  "Optimized something nobody asked for",
  "Added TODOs for my future self",
  "Fixed bug... introduced two more",
  "Because YOLO",
  "Fixed a bug. No idea how, but it works now 🤷",
  "Made the code compile. Functionality is optional.",
  "Deleted half the code… performance improved 🚀",
  "Added a feature nobody asked for 😎",
  "Fixed the fix that fixed the fix 🌀",
  "Debugged in production, like a pro 👨‍💻🔥",
  "99 little bugs in the code, 99 bugs to fix… 🎵",
  "Ship it! We'll fix it later ⛵",
  "Commit first, think later 😬",
  "Refactored code to impress my rubber duck 🦆",
  "Works on my machine 💻",
  "Wrote TODOs I’ll never do 📝",
  "Added comments so future me can suffer less 😅",
  "Renamed variables to confuse my teammates 🤡",
  "Finally removed console.log (probably not)",
  "Works on my machine 💻",
  "Commiting changes I don’t understand",
  "Changed stuff until it broke, then fixed it accidentally",
  "Added console.log for debugging 🔥",
  "Removed console.log for professionalism",
  "Added one line of code, broke everything",
  "Fixed typo in variable name after 2 hours of debugging",
  "Pushed directly to main like a rebel 🤘",
  "Finally fixed the infinite loop... I think",
  "Bug or feature? You decide",
  "The code fairy visited last night ✨",
  "This is fine 🔥🐶",
  "Hotfix for the hotfix",
  "Temporarily fixed it permanently",
  "Moved code around. Now it’s artistic",
  "Added comments that explain nothing",
  "Made naming more confusing",
  "Fixed merge conflict with violence",
  "Here be dragons 🐉",
  "Hacky but it works ¯\\_(ツ)_/¯",
  "Deleted node_modules (again)",
  "Fixed the matrix glitch 🕶️",
  "Updated dependencies. Pray for us 🙏",
  "Wrote code drunk, debugging sober",
  "Magic. Don’t touch ✨",
  "The commit police made me do this 🚨",
  "Turned coffee into code ☕➡️💻",
  "Ship it 🚢",
  "Added Easter egg nobody will find 🥚",
  "Commit message not found 404!",
  "Half-baked feature added 🍞",
  "Accidentally wrote a feature instead of fixing bug",
  "Fixed everything by deleting everything",
  "I have no idea what I'm doing 🐒",
  "Commented out more than I coded",
  "Made Git cry 😢",
  "Cowboy coding 🤠",
  "Fixed one thing, broke ten",
  "Improved performance by making it slower",
  "Linting gods are angry 😡",
  "First try! (not really)",
  "Debugging is just removing 'not' from if statements",
  "Just winging it 🪽",
  "Added memes instead of features",
  "Code written by ChatGPT 🤖",
  "This commit is classified 🕵️",
  "Hired StackOverflow developers 👨‍💻",
  "Fixed bug with duct tape and prayers",
  "CTRL+C CTRL+V driven development",
  "Code quality: questionable 🤔",
  "If it compiles, ship it",
  "Made something that looks like work",
  "The build passed! 🥳",
  "The build failed... but we ignore it 😬",
  "Replaced tabs with spaces (fight me)",
  "Space bar warrior",
  "Tried to center a div, gave up",
  "Improved code readability by deleting it",
  "Reinvented the wheel, square edition ⬛",
  "Everything is temporary, even this commit",
  "Updated README because that’s all I can do",
  "Added feature nobody asked for",
  "Accidental genius or intentional stupidity?",
  "Copy-pasted from StackOverflow",
  "Working prototype (aka total mess)",
  "Fixed bug at 3 AM 🌙",
  "I regret everything about this code",
  "Half commit, half prayer 🙏",
  "Added a feature that breaks another feature",
  "Debugging gods, please help",
  "I’ll fix it tomorrow (never)",
  "Made the code worse but prettier",
  "Added more bugs for job security",
  "Quick fix (aka permanent bug)",
  "Fixed typo in commit message",
  "Accidentally committed my soul to Git",
  "Fixed bug, created 99 more 🐛",
  "Made the code compile, not sure if it works",
  "Refactored code to look busy",
  "Optimized something nobody asked for",
  "Fixed typo that broke everything",
  "Removed console.log for professionalism",
  "Added console.log for debugging 🔥",
  "Half commit, half prayer 🙏",
  "Copy-pasted from StackOverflow",
  "Added a feature nobody asked for ✨",
  "Bug is now a feature 🐞➡️🚀",
  "Fixed the fix that broke the fix 🔄",
  "Wrote code drunk, debugged sober 🍺",
  "Hotfix for the hotfix 🔥",
  "Renamed variable to something cooler 😎",
  "Temporarily fixed… permanently 🤫",
  "Added console.log because I’m lost 🧭",
  "Deleted half the code, app runs faster ⚡",
  "Hacky but works 🤷‍♂️",
  "Works locally, not in prod 🙃",
  "Commiting like there’s no tomorrow ⏳",
  "Updated README to look busy 📖",
  "Removed code that looked at me funny 👀",
  "Made the linter cry 😢",
  "Refactored until nothing made sense 🔀",
  "Half code, half duct tape 🛠️",
  "Debugging with print statements… again 🖨️",
  "Version bump because why not 🔼",
  "Fixed something… I think 🤔",
  "Accidentally fixed the real bug 😳",
  "99 little bugs in the code 🎶",
  "It’s not a bug, it’s a surprise feature 🎁",
  "Forgot what I was doing, but committed anyway 🤯",
  "Fix works only if you don’t look too closely 👓",
  "Ctrl+C, Ctrl+V driven development ⌨️",
  "This commit is self-aware 🤖",
  "Code so clean it squeaks 🧼",
  "Added unicorns 🦄 to production",
  "Deleted production database, oops 💥",
  "Changed something and it actually worked 🎉",
  "Added more chaos to the system 🌀",
  "Oops, forgot to test… again 😬",
  "Fixed typo in code, introduced typo in life ✍️",
  "Tried turning it off and on again 🔄",
  "Cowboy coding at its finest 🤠",
  "Copied from StackOverflow, blessed by Google 🙏",
  "Magic numbers everywhere ✨🔢",
  "Wrote one line of code, took 3 hours ⏰",
  "Brb, sacrificing RAM to the code gods 🐏",
  "Fixed bug on line 42, universe still intact 🌌",
  "Made it worse but prettier 🎨",
  "Commented out everything until it worked 📝",
  "Quick fix before boss sees 👀",
  "Who needs unit tests anyway 🤡",
  "My code is now sentient 🤖",
  "Running on hope and duct tape 🪛",
  "Commit message not found ❓",
  "Refactored into spaghetti 2.0 🍝",
  "Debugging my debugging 🪲",
  "Tested in production ✅❌",
  "It compiled. That’s enough. ✔️",
  "Optimized for vibes, not performance ✌️",
  "Tried something new, regret everything 😭",
  "Accidentally wrote good code 😳",
  "This commit is sponsored by caffeine ☕",
  "It works, don’t touch it 🛑",
  "Half-baked solution, fully deployed 🍪",
  "Renamed file, broke entire system 💥",
  "This is why we can’t have nice things 😒",
  "Removed unnecessary commas, life feels lighter now 😌",
  "Turned spaghetti into ramen 🍜",
  "Bug found, bug ignored 🚷",
  "Made the code 200% more confusing 🔀",
  "Blame it on the last guy 👈",
  "Deleted logs so it looks clean 🧹",
  "If it works, it works 🧩",
  "Trial and error, mostly error ⚡",
  "Keyboard smashing driven development 🔨⌨️",
  "Added feature, forgot documentation 📚",
  "Not tested, but looks fine 👌",
  "Applied dark magic, code survived 🧙‍♂️",
  "Fixed alignment, broke functionality 📏",
  "Merge conflict? Nah, merge chaos ⚔️",
  "Sacrificed readability for performance 🚀",
  "Hardcoded everything, future me will suffer 😭",
  "Removed all comments, clean slate 🧽",
  "One does not simply write bug-free code 🧝‍♂️",
  "My code needs therapy 🛋️",
  "Infinite loop of sadness 🔄😭",
  "Solved problem by ignoring it 🕶️",
  "Put bandaid on open heart surgery 🩹",
  "Why does this even work? 🤨",
  "Lost in recursion forever 🔁",
  "Spoke to the rubber duck, still confused 🦆",
  "Fixed nothing but changed everything 🔧",
  "Added one line, broke 100 🧨",
  "Code is now allergic to production 🤧",
  "Refactored variable names to emojis 😂",
  "Achievement unlocked: infinite bugs 🏆",
  "Changed everything, fixed nothing 🔄",
  "Applied duct tape solution 🩹",
  "Made bugs immortal 🐛✨",
  "Accidentally solved world hunger 🍔",
  "Added TODO for future archaeologists 🏺",
  "Why is this working?? 🤯",
  "Debugged by crying 😢",
  "Works on my localhost café ☕",
  "Added more chaos to the matrix 🕶️",
  "Blame cosmic rays for the bug 🌌",
  "This line was written under pressure ⏱️",
  "Deleted something important… oops 🤦",
  "Code is now officially haunted 👻",
  "Bug is now a religion 🙏",
  "Renamed everything to 'thing' 🔤",
  "Removed gravity, now code floats 🌍🚀",
  "Copied from AI, hope it’s correct 🤖",
  "Logic was found missing 🔍",
  "It’s not broken, it’s just misunderstood 🥲",
  "Optimized for Mars deployment 🪐",
  "Bug escaped into production 🚪",
  "Deleted internet explorer support 🗑️",
  "Turned code into abstract art 🎨",
  "Replaced if-else with maybe 🤔",
  "Added smiley faces for motivation 🙂",
  "Hotfix? More like hot mess 🔥",
  "Magic happens here ✨",
  "Bugs are features with extra steps 🐞➡️🎉",
  "AI wrote this commit while I napped 😴",
  "Rebooted brain, code still broken 🧠💥",
  "Forgot to loop again",
  "Accidentally fixed the real bug 😳",
  "Applied duct tape solution 🩹",
  "Forgot to console.log again",
  "Implemented test with duct tape",
  "Put bandaid on open heart surgery 🩹",
  "This line was written under pressure ⏱️",
  "Fixed password but broke typo",
  "coffee driven development",
  "Implemented backend with duct tape",
  "Made the code 200% more confusing 🔀",
  "Renamed div to function",
  "Oops, loop is missing",
  "Magic happens here ✨",
  "typo driven development",
  "semicolon driven development",
  "Hardcoded function for now",
  "One does not simply write bug-free code 🧝‍♂️",
  "Forgot to bug again",
  "It works, don’t touch it 🛑",
  "Rebooted brain, code still broken 🧠💥",
  "Added bug because why not",
  "Oops, button is missing",
  "Why is this working?? 🤯",
  "Lost in recursion forever 🔁",
  "Version bump because why not 🔼",
  "Renamed button to README",
  "Implemented variable with duct tape",
  "Renamed div to database",
  "Added feature because why not",
  "Hardcoded variable for now",
  "Implemented password with duct tape",
  "Trial and error, mostly error ⚡",
  "Added variable because why not",
  "Renamed variable to feature",
  "Forgot to coffee again",
  "config driven development",
  "Code is now officially haunted 👻",
  "Added TODOs for my future self",
  "Renamed typo to config",
  "Added div because why not",
  "Merge conflict? Nah, merge chaos ⚔️",
  "Refactored code to look busy",
  "Fixed typo but broke database",
  "Implemented index.js with duct tape",
  "Fixed bug, created 99 more 🐛",
  "Oops, forgot to save before commit",
  "Achievement unlocked: infinite bugs 🏆",
  "Forgot to button again",
  "Hardcoded div for now",
  "Forgot to backend again",
  "Hardcoded hack for now",
  "function driven development",
  "Deleted internet explorer support 🗑️",
  "Removed semicolon accidentally",
  "Works on my localhost café ☕",
  "Optimized for Mars deployment 🪐",
  "Oops, backend is missing",
  "Debugging with print statements… again 🖨️",
  "It’s not broken, it’s just misunderstood 🥲",
  "Blame cosmic rays for the bug 🌌",
  "Added semicolon because why not",
  "Added password because why not",
  "Fixed index.js but broke bug",
  "Fixed loop but broke loop",
  "hack driven development",
  "Renamed variable to typo",
  "Oops, hack is missing",
  "Fixed feature but broke typo",
  "Fixed config but broke semicolon",
  "My code is now sentient 🤖",
  "Renamed file, broke entire system 💥",
  "Fixed bug... introduced two more",
  "Commit message not found ❓",
  "Forgot to typo again",
  "Accidentally solved world hunger 🍔",
  "Removed backend accidentally",
  "Renamed button to semicolon",
  "Bugs are features with extra steps 🐞➡️🎉",
  "Bug found, bug ignored 🚷",
  "Renamed config to semicolon",
  "Oops, semicolon is missing",
  "Forgot to database again",
  "Removed all comments, clean slate 🧽",
  "This is why we can’t have nice things 😒",
  "Removed config accidentally",
  "Removed hack accidentally",
  "Hardcoded semicolon for now",
  "Fixed README but broke index.js",
  "Hardcoded everything, future me will suffer 😭",
  "Made bugs immortal 🐛✨",
  "Oops, config is missing",
  "Renamed hack to database",
  "Removed bug accidentally",
  "Debugged by crying 😢",
  "Removed feature accidentally",
  "Fixed feature but broke password",
  "Removed README accidentally",
  "Blame it on the last guy 👈",
  "Hardcoded coffee for now",
  "My code needs therapy 🛋️",
  "Added smiley faces for motivation 🙂",
  "Renamed database to div",
  "Refactored variable names to emojis 😂",
  "database driven development",
  "Added more chaos to the matrix 🕶️",
  "Oops, database is missing",
  "Spoke to the rubber duck, still confused 🦆",
  "Code is now allergic to production 🤧",
  "Fixed config but broke typo",
  "Deleted production database, oops 💥",
  "Replaced if-else with maybe 🤔",
  "Not tested, but looks fine 👌",
  "Optimized something nobody asked for",
  "Fixed alignment, broke functionality 📏",
  "Removed gravity, now code floats 🌍🚀",
  "Refactored into spaghetti 2.0 🍝",
  "Renamed semicolon to config",
  "AI wrote this commit while I napped 😴",
  "If it works, it works 🧩",
  "Bug is now a religion 🙏",
  "Fixed config but broke div",
  "test driven development",
  "variable driven development",
  "Made the code compile, not sure if it works",
  "Fixed semicolon but broke semicolon",
  "Half-baked solution, fully deployed 🍪",
  "Hardcoded typo for now",
  "Fixed config but broke feature",
  "Because YOLO",
  "Oops, variable is missing",
  "Solved problem by ignoring it 🕶️",
  "Removed coffee accidentally",
  "Added loop because why not",
  "Removed typo accidentally",
  "Changed everything, fixed nothing 🔄",
  "Renamed password to backend",
  "Fixed test but broke function",
  "Implemented function with duct tape",
  "Infinite loop of sadness 🔄😭",
  "Renamed variable to password",
  "Sacrificed readability for performance 🚀",
  "feature driven development",
  "Forgot to password again",
  "Renamed div to test",
  "Renamed everything to 'thing' 🔤",
  "Forgot to test again",
  "Oops, test is missing",
  "Added hack because why not",
  "Works on my machine 💻",
  "Fixed nothing but changed everything 🔧",
  "Hardcoded README for now",
  "Added backend because why not",
  "Deleted something important… oops 🤦",
  "loop driven development",
  "Forgot to div again",
  "Implemented README with duct tape",
  "Oops, div is missing",
  "Fixed database but broke variable",
  "Added semicolon because life needs balance ;)",
  "Implemented database with duct tape",
  "Logic was found missing 🔍",
  "Applied dark magic, code survived 🧙‍♂️",
  "Added one line, broke 100 🧨",
  "Renamed button to feature",
  "Why does this even work? 🤨",
  "Implemented typo with duct tape",
  "Copied from AI, hope it’s correct 🤖",
  "Added TODO for future archaeologists 🏺",
  "Turned code into abstract art 🎨",
  "Removed password accidentally",
  "Added button because why not",
  "Removed div accidentally",
  "Fixed config but broke variable",
  "Hotfix? More like hot mess 🔥",
  "Removed database accidentally",
  "Bug escaped into production 🚪",
  "Fixed bug. Added two more in the process. You're welcome.",
  "Now it compiles. Whether it runs is another story...",
  "Refactored the refactor. Still ugly.",
  "Hotfix for the hotfix that broke the hotfix.",
  "This commit is self-aware. 👀",
  "Magic numbers removed. Added mystical constants instead.",
  "Deleted 100 lines of code… and it still works somehow.",
  "Implemented a feature nobody asked for but I like it.",
  "Improved performance by slowing everything else down.",
  "Fixed typo. Probably introduced ten more.",
  "I have no idea why this works. Do not touch.",
  "Added TODO comments. Future me can deal with it.",
  "Testing in production, what could go wrong?",
  "If this breaks, I was never here.",
  "99 bugs in the code, take one down, patch it around...",
  "Commit message not found. Please try again later.",
  "Changed variable names to something cooler 😎",
  "Half the tests pass. The other half are just wrong.",
  "Moved code around so Git thinks I did something.",
  "Applied duct tape solution. Should hold for now.",
  "Code works on my machine. Good luck elsewhere.",
  "Deleted important file. Oops. Restored from Stack Overflow.",
  "Added feature flag that does nothing but looks cool.",
  "Set all warnings to errors. Chaos ensued.",
  "Temporary fix… permanent problem.",
  "Hardcoded everything. Ship it!",
  "Removed console.logs. The app immediately broke.",
  "Version 2.0: same bugs, better excuses.",
  "Renamed variables for better readability. Now I can’t read them.",
  "Optimized algorithm… now takes twice as long.",
  "I swear this made sense at 3 AM.",
  "Just pressed random keys until it compiled.",
  "Migrated to new framework. Broke everything.",
  "Made the UI responsive. To my cat walking on the keyboard.",
  "Added Easter egg nobody will ever find.",
  "This commit is dedicated to future archaeologists of my code.",
  "Fixed merge conflict by deleting everything.",
  "Security fix: replaced HTTPS with ‘trust me bro’.",
  "Improved error messages: now they’re funnier.",
  "Unit tests? Nah, I believe in integration prayers."
];

const newfunnyCommits = [...new Set(funnyCommits)];

export default newfunnyCommits;